pin "@hotwired/turbo", to: "https://cdn.jsdelivr.net/npm/@hotwired/turbo@8.0.23/dist/turbo.es2017-esm.js"
pin "@hotwired/stimulus", to: "https://cdn.jsdelivr.net/npm/@hotwired/stimulus@3.2.2/dist/stimulus.js"
pin "rails_memory_profiler",                                to: "rails_memory_profiler/application.js"
pin "rails_memory_profiler/controllers",                    to: "rails_memory_profiler/controllers/index.js"
pin "rails_memory_profiler/controllers/application",        to: "rails_memory_profiler/controllers/application.js"
pin "rails_memory_profiler/controllers/filter_controller",  to: "rails_memory_profiler/controllers/filter_controller.js"
pin "rails_memory_profiler/controllers/compare_controller", to: "rails_memory_profiler/controllers/compare_controller.js"
